name: CI/CD self-hosted

on:
  push:
    branches: [ "tests-calculatrice" ]   # puis "main" plus tard

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -r requirements.txt
      - run: pytest -q

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with Docker (no SSH)
        run: |
          set -e
          docker build -t labo0-calculator .
          docker ps -q --filter "name=labo0-calculator" | xargs -r docker stop
          docker run -d --rm --name labo0-calculator labo0-calculator
          echo "Conteneur démarré."