name: CI/CD self-hosted

on:
  push:
    branches: [ "tests-calculatrice" ]   # puis "main" plus tard

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -r requirements.txt
      - run: pytest -q

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy locally (no SSH)
        run: |
          set -e
          python3 -m venv .venv/labo0 || true
          . .venv/labo0/bin/activate
          pip install -r requirements.txt
          pkill -f "python src/calculator.py" || true
          nohup python src/calculator.py > /tmp/calculator.log 2>&1 &
          echo "Déployé. Logs: /tmp/calculator.log"